image: alpine:latest

pages:
  stage: deploy
  script:
    - mkdir public
    - cp -r index.html NagiSwipe-main.css NagiSwipe-main.js img public/
  artifacts:
    paths:
      - public
  only:
    - main
